---
title: "Digging Extra Plays"
author: "Ellen Martin"
date: "`r Sys.Date()`"
output: html_document
---

Analyzing Multiple Plays of Digging Game Data

```{r Libraries}
library(readr)
library(NatParksPalettes)
library(ggplot2)
library(Hmisc) #for computing correlation stuff
library(knitr) 
library(tidyverse, warn.conflict=F)
library(corrplot)
library(dplyr)
library(MASS)
library(sandwich)
library(lmtest)
library(broom)
library(dplyr)
library(gt)
library(lme4)
library(dunn.test)

source("poster_theme.R") #for figure themes
source("functions/process_initquiz.R")
source("functions/process_digging_long.R")
source("functions/process_params.R")
source("functions/softmax.R")


```

```{r Data Paths and Merging Data for Play 2 FIRST PLAY}
# data paths
# data_path <- "C:\\Users\\Ellen Martin\\OneDrive\\Desktop\\Rutledge Lab\\ApathyDepression\\updatedData\\data\\happyData\\"
data_path <- "~/Desktop/Rutledge Lab/ApathyDepression/updatedData/data/happyData/"

### play one for people with at least two plays - play 1
#one_long_file_z <- paste0(data_path,"z\\THP_uk_DiggingHappy2_first_z_n2194.csv") #zscored
one_long_file_z <- paste0(data_path,"z/THP_uk_DiggingHappy2_first_z_n2194.csv") #zscored


### parameters and model fits data
#happy_file_one_z <- paste0(data_path, "modelBased\\z\\happy_params4_play2_first_z_n2194.csv")
happy_file_one_z <- paste0(data_path, "modelBased/z/happy_params4_play2_first_z_n2194.csv")


### survey data
#survey_file <- paste0("C:\\Users\\Ellen Martin\\OneDrive\\Desktop\\Rutledge Lab\\ApathyDepression\\updatedData\\analyses\\uk_general_survey.csv")
survey_file <- paste0("~/Desktop/Rutledge Lab/ApathyDepression/updatedData/analyses/uk_general_survey.csv")

### initial quiz data
initquiz_file <- paste0(data_path, "THP_uk_initquiz.csv")

# cleaning and merging data
T_digging_long_z <- process_digging_long_z(one_long_file_z)
length(unique(T_digging_long_z$userKey)) #N=2190

T_digging_long_z <- process_params_z(T_digging_long_z,happy_file_one_z)
length(unique(T_digging_long_z$userKey)) #2190
head(T_digging_long_z)

happyData1 <- process_survey_data(T_digging_long_z,survey_file)

happyData1 <- happyData1 %>%
  arrange(userKey, PlayNo, TrialNumber)


### backfill z-scored
happyData1 <- happyData1 %>%
  mutate(zHappy_filled = zHappy) %>%
  fill(zHappy_filled, .direction = "up")

happyData1 <- happyData1 %>%
  mutate(zHappyPred_filled = zHappyPred) %>%
  fill(zHappyPred_filled, .direction = "up")

length(unique(happyData1$userKey)) #1921

### GAD and PHQ bins
happyData1 <- happyData1 %>%
  mutate(GAD_bin = cut(gad7_total, breaks = c(-Inf, 4, 9, 14, 21), labels = c("0-4", "5-9", "10-14", "15-21")),
      PHQ_bin = cut(phq8_total, breaks = c(-Inf, 4, 9, 14, 24), labels = c("0-4", "5-9", "10-14", "15-24")),
      GAD_binary = case_when(gad7_total >= 6 ~ "GAD 6+",
                             gad7_total < 6 ~ "GAD <6"),
      PHQ_binary = case_when(phq8_total >= 7 ~ "PHQ 7+",
                             phq8_total < 7 ~ "PHQ <7"))

# Anxiety and Depression Diagnoses Analyses
T_survey <- read_csv(survey_file)

diag <- T_survey %>%
  dplyr::select(c("diagnosis_depression","diagnosis_anxiety","userKey"))

head(diag)

happyData1_diag <- merge(happyData1, diag, by="userKey")

happyData1_diag <- happyData1_diag %>%
  filter(!is.na(diagnosis_anxiety) & !is.na(diagnosis_depression)) %>%
  mutate(diagnosis_anxiety = as.factor(diagnosis_anxiety),
         diagnosis_depression = as.factor(diagnosis_depression)) %>%
  mutate(diagnosis_anxiety = case_when(diagnosis_anxiety == 1 ~ "anx",
                                       diagnosis_anxiety == 0 ~ "no anx"),
         diagnosis_depression = case_when(diagnosis_depression == 1 ~ "dep",
                                          diagnosis_depression == 0 ~ "no dep"))


sample_size = length(unique(happyData1_diag$userKey)) # N = 1592

happyData1_diag$diagnosis_anxiety <- as.factor(happyData1_diag$diagnosis_anxiety)
happyData1_diag$diagnosis_depression <- as.factor(happyData1_diag$diagnosis_depression)
```

# Average Percentage of Gambling

```{r}
risky_data <- happyData1 %>%
    group_by(userKey, Trial) %>%
    summarise(total_choices = n(),
              risky_choices = sum(Choice == 2, na.rm = TRUE),
              percent_risky = (risky_choices / total_choices) * 100,
              .groups = 'drop')


summary_data <- risky_data %>%
    group_by(Trial) %>%
    summarise(mean_percent_risky = mean(percent_risky, na.rm = TRUE),
              se_percent_risky = sd(percent_risky, na.rm = TRUE) / sqrt(n()),
              .groups = 'drop')
  
### plot 

  ggplot(summary_data, aes(x = Trial, y = mean_percent_risky, color = Trial)) +
    geom_point(position = position_dodge(0.8), size = 3) +
    geom_errorbar(aes(ymin = mean_percent_risky - se_percent_risky, ymax = mean_percent_risky + se_percent_risky),
                  width = 0.2) +
    labs(
      title = paste0("% Risky Choices (Play 1) N at least 2 plays = ",sample_size,")"),
      x = "Trial Type",
      y = "% Risky Choices"
    ) +
    theme_minimal() +
    ylim(40, 60) +  
    poster_theme + 
    scale_color_manual(values = c("Gain" = "gold", "Loss" = "coral"))
  
  
```

```{r Data Paths and Merging Data for Play 3 THIRD PLAY}
# data paths
#data_path <- "C:\\Users\\Ellen Martin\\OneDrive\\Desktop\\Rutledge Lab\\ApathyDepression\\updatedData\\data\\happyData\\"
data_path <- "~/Desktop/Rutledge Lab/ApathyDepression/updatedData/data/happyData/"

### play one for people with at least two plays - play 1
#one_long_file_z <- paste0(data_path,"z\\THP_uk_DiggingHappy3_z_n960.csv") #zscored
one_long_file_z <- paste0(data_path,"z/THP_uk_DiggingHappy3_z_n960.csv") #zscored

### parameters and model fits data - for play 3 this is the 4 parameter model
#happy_file_one_z <- paste0(data_path, "modelBased\\z\\happy_params4_play3_z_n960.csv")
happy_file_one_z <- paste0(data_path, "modelBased/z/happy_params4_play3_z_n960.csv")


### parameters and model fits data - for play 3 this is the 6 parameter model
#happy_file_one_z_6 <- paste0(data_path, "modelBased\\z\\happy_params6_play3_z_n960.csv")
happy_file_one_z_6 <- paste0(data_path, "modelBased/z/happy_params6_play3_z_n960.csv")

### survey data
# survey_file <- paste0("C:\\Users\\Ellen Martin\\OneDrive\\Desktop\\Rutledge Lab\\ApathyDepression\\updatedData\\analyses\\uk_general_survey.csv")

survey_file <- paste0("~/Desktop/Rutledge Lab/ApathyDepression/updatedData/analyses/uk_general_survey.csv")

### initial quiz data
initquiz_file <- paste0(data_path, "THP_uk_initquiz.csv")

# cleaning and merging data
T_digging_long_z <- process_digging_long_z(one_long_file_z)
length(unique(T_digging_long_z$userKey)) #N=2190

T_digging_long_z <- process_params_z(T_digging_long_z,happy_file_one_z)
length(unique(T_digging_long_z$userKey)) #2190
head(T_digging_long_z)

happyData1 <- process_survey_data(T_digging_long_z,survey_file)

happyData1 <- happyData1 %>%
  arrange(userKey, PlayNo, TrialNumber)


### backfill z-scored
happyData1 <- happyData1 %>%
  mutate(zHappy_filled = zHappy) %>%
  fill(zHappy_filled, .direction = "up")

happyData1 <- happyData1 %>%
  mutate(zHappyPred_filled = zHappyPred) %>%
  fill(zHappyPred_filled, .direction = "up")

length(unique(happyData1$userKey)) #1921

### GAD and PHQ bins
happyData1 <- happyData1 %>%
  mutate(GAD_bin = cut(gad7_total, breaks = c(-Inf, 4, 9, 14, 21), labels = c("0-4", "5-9", "10-14", "15-21")),
      PHQ_bin = cut(phq8_total, breaks = c(-Inf, 4, 9, 14, 24), labels = c("0-4", "5-9", "10-14", "15-24")),
      GAD_binary = case_when(gad7_total >= 6 ~ "GAD 6+",
                             gad7_total < 6 ~ "GAD <6"),
      PHQ_binary = case_when(phq8_total >= 7 ~ "PHQ 7+",
                             phq8_total < 7 ~ "PHQ <7"))

# Anxiety and Depression Diagnoses Analyses
T_survey <- read_csv(survey_file)

diag <- T_survey %>%
  dplyr::select(c("diagnosis_depression","diagnosis_anxiety","userKey"))

head(diag)

happyData1_diag <- merge(happyData1, diag, by="userKey")

happyData1_diag <- happyData1_diag %>%
  filter(!is.na(diagnosis_anxiety) & !is.na(diagnosis_depression)) %>%
  mutate(diagnosis_anxiety = as.factor(diagnosis_anxiety),
         diagnosis_depression = as.factor(diagnosis_depression)) %>%
  mutate(diagnosis_anxiety = case_when(diagnosis_anxiety == 1 ~ "anx",
                                       diagnosis_anxiety == 0 ~ "no anx"),
         diagnosis_depression = case_when(diagnosis_depression == 1 ~ "dep",
                                          diagnosis_depression == 0 ~ "no dep"))


sample_size  = (unique(happyData1_diag$userKey)) # N = 1592

happyData1_diag$diagnosis_anxiety <- as.factor(happyData1_diag$diagnosis_anxiety)
happyData1_diag$diagnosis_depression <- as.factor(happyData1_diag$diagnosis_depression)

# past
happyData1_past <- happyData1 %>%
  arrange(userKey, TrialNumber) %>%
  group_by(userKey) %>%
  mutate(
    # Create an indicator for valid happiness ratings
    happyind = !is.na(zHappy),
    
    # Identify if the current trial is on the same island as the previous valid happiness rating
    prev_happyind_trial = lag(Trial, order_by = TrialNumber),  # Previous trial type (Gain/Loss)
    
    # Set PastIsland based on the previous valid happiness rating's trial type
    PastIsland = case_when(
      lag(happyind, order_by = TrialNumber) & prev_happyind_trial == "Gain" ~ 2,
      lag(happyind, order_by = TrialNumber) & prev_happyind_trial == "Loss" ~ 1,
      TRUE ~ NA_real_  # NA for the first island or no previous valid row
    )
  ) %>%
  ungroup()

happyData1_past <- happyData1_past %>%
  fill(PastIsland, .direction = "up")

sample_size = length(unique(happyData1$userKey))
```

```{r}
params6 <- read.csv(happy_file_one_z_6)
params_multi <- params6 %>%
    rename(
      ev_safe = b_evrpe_1,
      rpe_safe = b_evrpe_2,
      ev_risky = b_evrpe_3,
      rpe_risky = b_evrpe_4,
      tau_split = b_evrpe_5,
      const_split = b_evrpe_6,
      r2_split = r2,
      sse_split = sse,
      aic_split = aic,
      bic_split =bic
    )

happyData1_6 <- merge(happyData1, params_multi, by="userKey")
mean(params_multi$r2_split)
mean(params_multi$aic_split)
mean(params_multi$bic_split)

# mean tau and baseline happiness

mean(params_multi$tau_split) 
mean(params_multi$const_split)

cor.test(params_multi$ev_risky,params_multi$ev_safe,method="spearman")
cor.test(params_multi$rpe_risky,params_multi$rpe_safe,method="spearman")
cor.test(params_multi$rpe_risky,params_multi$ev_risky,method="spearman")
cor.test(params_multi$rpe_safe,params_multi$ev_safe,method="spearman")
```


# Average Percentage of Gambling

```{r}
risky_data <- happyData1 %>%
    group_by(userKey, Trial) %>%
    summarise(total_choices = n(),
              risky_choices = sum(Choice == 2, na.rm = TRUE),
              percent_risky = (risky_choices / total_choices) * 100,
              .groups = 'drop')


summary_data <- risky_data %>%
    group_by(Trial) %>%
    summarise(mean_percent_risky = mean(percent_risky, na.rm = TRUE),
              se_percent_risky = sd(percent_risky, na.rm = TRUE) / sqrt(n()),
              .groups = 'drop')
  
### plot 

  ggplot(summary_data, aes(x = Trial, y = mean_percent_risky, color = Trial)) +
    geom_point(position = position_dodge(0.8), size = 3) +
    geom_errorbar(aes(ymin = mean_percent_risky - se_percent_risky, ymax = mean_percent_risky + se_percent_risky),
                  width = 0.2) +
    labs(
      title = "% Risky Choices (Play 3) N=872",
      x = "Trial Type",
      y = "% Risky Choices"
    ) +
    theme_minimal() +
    ylim(40, 60) +  
    poster_theme + 
    scale_color_manual(values = c("Gain" = "gold", "Loss" = "coral"))
  
  
  
```